#!/bin/bash

xsetroot -cursor_name left_ptr
sxhkd &
xset r rate 200 60

# Set monitor names
bspc monitor -d Terminal Browser Discord Sublime 010 VI VII Burp Net Rev

bspc rule -a brave-browser desktop=Browser follow=on

bspc config normal_border_color "#ddd"
bspc config focused_border_color "#ff9900"
bspc config border_width	1
bspc config window_gap		12

bspc config split_ratio		1
bspc config focus_follows_pointer	true
bspc config pointer_modifier	mod1

bspc config automatic_scheme	spiral

feh --bg-center .config/bspwm/precedens.png

# Enable compositing for transparrent scratchpads
picom --backend xrender &
$HOME/.config/polybar/launch.sh &
(xdo id -m -N Polybar && polybar-msg cmd hide) &
