#cloud-config
#https://canonical-subiquity.readthedocs-hosted.com/en/latest/reference/autoinstall-reference.html
autoinstall:
  version: 1
  locale: en_US
  timezone: "Europe/London"
  keyboard:
    layout: us
  storage:
    layout:
      name: storage
  identity:
    realname: "User"
    hostname: machine
    username: user
    password: '$y$j9T$dfB3gvSzWbywFLuEY15TV0$VBoOaUE.lle02VOJlI220NRprHMTQQEx2BhS2I5Wc31'
  snap:
    - name: discord
      classic: true
  packages:
    - ripgrep
    - zsh
    - git
    - curl
    - kitty
    - vim
    - rsync
    - python3-pip
    - openvpn
    - python3-olefile
    - python3-virtualenv
    - neofetch
    - rofi
    - copyq
    - xbacklight
    - maim
    - picom
    - p7zip-full
    - flameshot
    - remmina
    - wireguard-tools
    - nmap
    - tshark
    - qrencode
    - dirb
    - ffuf
    - arandr
    - binwalk
    - feh
    - bspwm
    - sxhkd
    - btop
    - xdotool
    - polybar
    - curl
    - gnupg
    - python3-dev
    - libssl-dev
    - libffi-dev
    - build-essential
    - eza
    - unzip
    - make
    - papirus-icon-theme
  late-commands:
    - curtin in-target --target=/target -- apt update
    - curtin in-target --target=/target -- bash -c 'curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg'
    - curtin in-target --target=/target -- bash -c 'echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list'
    - curtin in-target --target=/target -- apt update
    - curtin in-target --target=/target -- apt install -y brave-browser
    - curtin in-target --target=/target -- bash -c 'echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers'
  user-data:
    runcmd:
      - bash -c "cd /tmp && git clone https://github.com/noctuid/tdrop.git"
      - bash -c "cd /tmp/tdrop && make install"
      - bash -c "git clone --depth 1 https://github.com/junegunn/fzf.git /opt/fzf"
      - bash -c "/opt/fzf/install --all"
      - bash -c 'export RUNZSH=no; export CHSH=no; su - user -c "sh -c \"\$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\""'
      - curl -L git.io/antigen > /home/user/.antigen.zsh
      - chsh -s /usr/bin/zsh user
      - bash -c 'su - user -c "curl -fsSL http://autoinstall.6l.dk/dotfiles -o /tmp/dotfiles.zip && unzip -o /tmp/dotfiles.zip -d /home/user/"'
      - python3 -m pip install --upgrade pip
      - python3 -m pip install --upgrade pwntools
      - chmod +x /home/user/.config/bspwm/bspwmrc
      - chmod +x /home/user/.config/polybar/launch.sh